version: '3'
services:
  nginx:
    image: jwilder/nginx-proxy:alpine
    network_mode: bridge
    ports:
      - '8080:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  ui-vuejs:
    image: nginx:alpine
    network_mode: bridge
    environment:
      - VIRTUAL_HOST=${PROJECT_URL}
    volumes:
      - ./dist:/usr/share/nginx/html
  ui-vuejs-dev:
    image: marvinenf/vuejs-dev
    command: sh -c "npm run serve"
    network_mode: bridge
    volumes:
      - ./:/var/www/html/app
